/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface StreamInterface extends utils.Interface {
  functions: {
    "claimVestedTokens(address)": FunctionFragment;
    "fixVestingSchedule()": FunctionFragment;
    "userVestedClaim()": FunctionFragment;
    "vestedTokens()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "claimVestedTokens"
      | "fixVestingSchedule"
      | "userVestedClaim"
      | "vestedTokens"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claimVestedTokens",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "fixVestingSchedule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userVestedClaim",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vestedTokens",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "claimVestedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fixVestingSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userVestedClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestedTokens",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Stream extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: StreamInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    claimVestedTokens(
      _to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    fixVestingSchedule(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    userVestedClaim(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amount: BigNumber }>;

    vestedTokens(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amount: BigNumber }>;
  };

  claimVestedTokens(
    _to: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  fixVestingSchedule(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  userVestedClaim(overrides?: CallOverrides): Promise<BigNumber>;

  vestedTokens(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    claimVestedTokens(
      _to: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    fixVestingSchedule(overrides?: CallOverrides): Promise<void>;

    userVestedClaim(overrides?: CallOverrides): Promise<BigNumber>;

    vestedTokens(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    claimVestedTokens(
      _to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    fixVestingSchedule(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    userVestedClaim(overrides?: CallOverrides): Promise<BigNumber>;

    vestedTokens(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    claimVestedTokens(
      _to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    fixVestingSchedule(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    userVestedClaim(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    vestedTokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
